apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Files\Documents\Projects\Java\PR8\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mailer
  name: mailer
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8025
    - name: "1025"
      port: 1025
      targetPort: 1025
  selector:
    io.kompose.service: mailer
status:
  loadBalancer: {}
