apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Files\Documents\Projects\Java\PR8\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: notes-service
  name: notes-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: notes-service
status:
  loadBalancer: {}
