apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Files\Documents\Projects\Java\PR8\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: users-service
  name: users-service
spec:
  ports:
    - name: 8081-tcp
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: users-service
status:
  loadBalancer: {}
