server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: notes-service
          uri: lb://NOTES-SERVICE
          predicates:
            - Path=/notes/**
          filters:
            - StripPrefix=1

        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka