server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6dbd7fc114e779320245
            client-secret: 855280e2409fe0f7955aca7bcdf9aaf51923e4f5

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users-db
    username: user
    password: pass
    hikari.max-lifetime: 60000
    hikari.connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka